# .github/workflows/entrar.yml
name: Entrar a Sala HaxBall

on:
  workflow_dispatch:  # Solo manual

jobs:
  entrar:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm i puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Entrar a la sala (para siempre)
        env:
          ROOM_URL: ${{ secrets.ROOM_URL }}
        run: node tirar_sala.js
