# .github/workflows/run.yml
name: Cogedor de autistas

on:
  workflow_dispatch:   # Solo manual

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar puppeteer-extra + stealth
        run: |
          npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Ejecutar el bot
        run: node archivo.js
